Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: lambda.Register
      CodeUri: /Users/hoando/Desktop/BYU_F2022/CS340/TweetServer
      Runtime: java11
      Architectures:
        - arm64